# -*- coding: utf-8 -*-
"""ProjetoFinalIA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wvN6p_9H7QgxQye9EwcUTlv28PjoQbfg

Baixando o repositório de dados
"""

!wget https://archive.ics.uci.edu/static/public/240/human+activity+recognition+using+smartphones.zip -O uci_har.zip

!unzip -q uci_har.zip
!unzip -q "UCI HAR Dataset.zip"

"""Importando bibliotecas"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

dataset_path = "UCI HAR Dataset/"

"""Mapeamento dos rótulos de atividades"""

activity_labels = {
    1: 'WALKING',
    2: 'WALKING_UPSTAIRS',
    3: 'WALKING_DOWNSTAIRS',
    4: 'SITTING',
    5: 'STANDING',
    6: 'LAYING'
}

"""Carregamento dos conjuntos de Treino e Teste"""

X_train = pd.read_csv(dataset_path + "train/X_train.txt", delim_whitespace=True, header=None)
y_train = pd.read_csv(dataset_path + "train/y_train.txt", delim_whitespace=True, header=None, names=['Activity'])

X_test = pd.read_csv(dataset_path + "test/X_test.txt", delim_whitespace=True, header=None)
y_test = pd.read_csv(dataset_path + "test/y_test.txt", delim_whitespace=True, header=None, names=['Activity'])

"""Mapear os números para os nomes das atividades"""

y_train['Activity_Name'] = y_train['Activity'].map(activity_labels)
y_test['Activity_Name'] = y_test['Activity'].map(activity_labels)

"""Verificação das dimensões e dados ausentes"""

print(f"X_train: {X_train.shape} (amostras, atributos)")
print(f"X_test:  {X_test.shape} (amostras, atributos)")
print(f"Valores nulos em X_train: {X_train.isnull().sum().sum()}")
print(f"Valores nulos em X_test:  {X_test.isnull().sum().sum()}")

"""Normalização Linear"""

X_train_min = X_train.min()
X_train_max = X_train.max()

range_val = np.where((X_train_max - X_train_min) == 0, 1, (X_train_max - X_train_min))
X_train_norm = (X_train - X_train_min) / range_val

X_test_norm = (X_test - X_train_min) / range_val

"""Estatísticas Descritivas de 1ª e 2ª Ordem (Média, Desvio Padrão, Mín, Máx)"""

selected_cols = X_train_norm.iloc[:, :10]
stats_df = pd.DataFrame({
    'Média (1ª ordem)': selected_cols.mean(),
    'Variância (2ª ordem)': selected_cols.var(),
    'Desvio Padrão (2ª ordem)': selected_cols.std()
})

print("\n--- ESTATÍSTICAS DE 1ª E 2ª ORDEM (Primeiros 10 Atributos) ---")
print(stats_df)

"""Distribuição"""

plt.figure(figsize=(10, 4))
sns.countplot(data=y_train, x='Activity_Name', order=activity_labels.values(), palette='viridis')
plt.title('Distribuição das Atividades no Conjunto de Treinamento')
plt.xlabel('Atividade')
plt.ylabel('Quantidade de Amostras')
plt.xticks(rotation=25)
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()

"""Cálculo da Matriz de Covariância e Correlação de Pearson"""

cov_matrix = selected_cols.cov()
corr_matrix = selected_cols.corr()

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm', vmin=-1, vmax=1, cbar=True)
plt.title('Matriz de Correlação dos Atributos (Estatística de 2ª Ordem)')
plt.xlabel('Índice do Atributo')
plt.ylabel('Índice do Atributo')
plt.tight_layout()
plt.show()

"""Correlação entre os atributos dos sensores e as atividades"""

df_analysis = X_train_norm.iloc[:, :8].copy()

activity_dummies = pd.get_dummies(y_train['Activity_Name'])

df_combined = pd.concat([df_analysis, activity_dummies], axis=1)

"""Calcular a Matriz de Correlação e Heatmap"""

corr_combined = df_combined.corr()

plt.figure(figsize=(12, 10))
sns.heatmap(corr_combined, annot=True, fmt='.2f', cmap='coolwarm', vmin=-1, vmax=1, cbar=True)
plt.title('Matriz de Correlação: Sensores vs. Atividades Humanas')
plt.xticks(rotation=45, ha='right')
plt.yticks(rotation=0)
plt.tight_layout()
plt.show()